"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eucd2$q^jr+1ea)8(8by&-p+%+c_u^w$#v&dc_x2_i1qk_q_(('

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True



# Application definition

INSTALLED_APPS = [
    
    # =========================
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ==================================
    'django.contrib.sites',
    'django.contrib.flatpages',
    'news.apps.NewsConfig',
    'accounts.apps.AccountsConfig',
    # =============================	
    # 
    # =============================
    'django_filters',
    'static',
    'signup',
    'users',
    'mail',
    # =========== allauth ============
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    # ===============================
    'django_apscheduler',
    
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # ====================================================
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    # request доступный в шаблонах
    'django.contrib.sites.middleware.CurrentSiteMiddleware',

]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # ================== request в шаблонах==============
                # 'news.context_processors.add_request_to_context',
                # =========== кэширование всего сайта =================
                # 'django.middleware.cache.UpdateCacheMiddleware',
                # 'django.middleware.common.CommonMiddleware',
                # 'django.middleware.cache.FetchFromCacheMiddleware',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATICFILES_DIRS = [
#     BASE_DIR / "static"
# ]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# LOGIN_URL = 'signup/login/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
   # Необходимо войти по имени пользователя в Django admin, 
   # независимо от `allauth`

   'django.contrib.auth.backends.ModelBackend',
  
   # специфические методы аутентификации "allauth", 
   # такие как вход по электронной почте

   'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

ALLOWED_HOSTS = [ '127.0.0.1',]

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.MailRegisterForm',
    'login': 'accounts.forms.MailLoginForm',
    'password_change': 'accounts.forms.PasswordChangeForm',
}

# EMAIL_HOST = 'smtp.yandex.ru'   # адрес сервера Яндекс-почты для всех один и тот же
# EMAIL_PORT = 465                # порт smtp сервера тоже одинаковый
# EMAIL_HOST_USER = ''            # ваше имя пользователя, например если ваша почта user@yandex.ru, то сюда надо писать
#                                 # user, иными словами, это всё то что идёт до собаки
# EMAIL_HOST_PASSWORD = ''        # пароль от почты
# EMAIL_USE_SSL = True            # Яндекс использует ssl, подробнее о том, что это, почитайте на Википедии, но
                                # включать его здесь обязательно

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True


EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = DEFAULT_FROM_EMAIL


    
# ===================== django_apscheduler ==================

# формат даты, которую будет воспринимать наш задачник(вспоминаем урок по фильтрам) 
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
 
# если задача не выполняется за 25 секунд, то она автоматически снимается, можете поставить время побольше, но как правило, это сильно бьёт по производительности сервера
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# ===================================================================

# ======================= Кэширование ============================
CACHES = {
    'default': {
        'TIMEOUT': 60,
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'), # Указываем, куда будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
        'OPTIONS': {
            'MAX_ENTRIES': 500
        }
    }
}

ADMINS = [('skillfactory.course', 'skillfactory.course@gmail.com'),]
          
# ('sub_admin', 'lek.dfv@mail.ru')
# ('skillfactory.course', 'skillfactory.course@gmail.com')
# ==========================================================================

import logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # форматирование
    'formatters': {
        'console_debug_format': {
            'format': '{asctime} | {levelname} | {message}',
            'style': '{',
        },
        
        'console_warning_format': {
            'format': '{asctime} | {levelname} | {message} | {pathname}',
            'style': '{',
        },
        
        'console_error_format': {
            'format': '{asctime} | {levelname} | {message} | {pathname} | {exc_info}',
            'style': '{',
        },
        
        'general_log_format': {
            'format': '{asctime} | {levelname} | {module} | {message}',
            'style': '{',
        },
        
        'errors_log_format': {
            'format': '{asctime} | {levelname} | {message} | {pathname} | {exc_info}',
            'style': '{',
        },
        
        'security_log_format': {
            'format': '{asctime} | {levelname} | {module} | {message}',
            'style': '{',
        },
        
        'mail_admins_format': {
            'format': '{asctime} | {levelname} | {message} | {pathname}',
            'style': '{',
        },
    },
    # ============================================================
   
    'filters': {
        'debug_true_filter': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'debug_false_filter': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    # ============================================================
    
    'handlers': {
        'console_debug_handler': {
            'level': 'DEBUG',
            'filters': ['debug_true_filter'],
            'class': 'logging.StreamHandler',
            'formatter': 'console_debug_format'
        },
        
        'console_warning_handler': {
            'level': 'WARNING',
            'filters': ['debug_true_filter'],
            'class': 'logging.StreamHandler',
            'formatter': 'console_warning_format'
        },
        
        'console_error_handler': {
            'level': 'ERROR',
            'filters': ['debug_true_filter'],
            'class': 'logging.StreamHandler',
            'formatter': 'console_error_format'
        },
        
        'general_log_handler': {
            'level': 'INFO',
            'filters': ['debug_false_filter'],
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'logger/general.log',
            'formatter': 'general_log_format',
        },
        
        'errors_log_handler': {
            'level': 'ERROR',
            # 'filters': ['debug_false_filter'],
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'logger/errors.log',
            'formatter': 'errors_log_format',
        },
        
        'security_log_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'logger/security.log',
            'formatter': 'security_log_format',
        },
        
        'mail_admins_handler': {
            'level': 'ERROR',
            'filters': ['debug_false_filter'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mail_admins_format',
            'email_backend': "django.core.mail.backends.smtp.EmailBackend",
            # "email_backend": "django.core.mail.backends.filebased.EmailBackend"
        },
    },
    # ==============================================================
    
    'loggers': {
        'django': {
            'handlers': ['console_debug_handler', 'console_warning_handler', 
                         'console_error_handler',  'general_log_handler', 'mail_admins_handler'],
            'level': 'DEBUG',
            'propagate': True,
        },
        
        'django.request': {
            'handlers': ['errors_log_handler', 'mail_admins_handler'],
            'level': 'ERROR',
            'propagate': True,
        },
        
        'django.server': {
            'handlers': ['errors_log_handler', 'mail_admins_handler'],
            'level': 'ERROR',
            'propagate': True,
        },
        
        'django.template': {
            'handlers': ['errors_log_handler',],
            'level': 'ERROR',
            'propagate': True,
        },
        
        'django.db_backends': {
            'handlers': ['errors_log_handler'],
            'level': 'ERROR',
            'propagate': True,
        },
        
        'django.security': {
            'handlers': ['security_log_handler'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# =====================================================

# В консоль должны выводиться все сообщения уровня DEBUG и выше, включающие время, уровень сообщения, сообщения. Для сообщений WARNING и выше дополнительно должен выводиться путь к источнику события (используется аргумент pathname в форматировании). А для сообщений ERROR и CRITICAL еще должен выводить стэк ошибки (аргумент exc_info). Сюда должны попадать все сообщения с основного логгера django.

# В файл general.log должны выводиться сообщения уровня INFO и выше только с указанием времени, уровня логирования, модуля, в котором возникло сообщение (аргумент module) и само сообщение. Сюда также попадают сообщения с регистратора django

# В файл errors.log должны выводиться сообщения только уровня ERROR и CRITICAL. В сообщении указывается время, уровень логирования, само сообщение, путь к источнику сообщения и стэк ошибки. В этот файл должны попадать сообщения только из логгеров django.request, django.server, django.template, django.db_backends.

# В файл security.log должны попадать только сообщения, связанные с безопасностью, а значит только из логгера django.security. Формат вывода предполагает время, уровень логирования, модуль и сообщение.

# На почту должны отправляться сообщения уровней ERROR и выше из django.request и django.server, по формату как в errors.log, но без стэка ошибок.

# Более того, при помощи фильтров указать, что в консоль сообщения отправляются только при DEBUG = True, а на почту и в файл general.log только при DEBUG = False.


# ==================================================================================

# Данный код устанавливает определенные параметры для модуля "django-allauth", который предоставляет функциональность для аутентификации пользователей в Django. 
#  1. ACCOUNT_EMAIL_REQUIRED = True - требуется ли адрес электронной почты для каждого пользователя. 
# 2. ACCOUNT_UNIQUE_EMAIL = True - требуется ли уникальный адрес электронной почты для каждого пользователя. 
# 3. ACCOUNT_USERNAME_REQUIRED = True - требуется ли имя пользователя для каждого пользователя. 
# 4. ACCOUNT_AUTHENTICATION_METHOD = 'username_email' - метод аутентификации, который позволяет пользователям входить в систему с помощью имени пользователя или адреса электронной почты. 
# 5. ACCOUNT_SESSION_REMEMBER = False - отключение функции "запомнить меня" при входе в систему. 
# 6. ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True - требование ввода пароля дважды при регистрации нового пользователя. 
# 7. ACCOUNT_EMAIL_VERIFICATION = 'mandatory' #- обязательное подтверждение адреса электронной почты при регистрации нового пользователя. 
# 8. ACCOUNT_CONFIRM_EMAIL_ON_GET = True - подтверждение адреса электронной почты при переходе по ссылке в электронном письме, отправленном пользователю.  
#  Каждый из этих параметров определяет, каким образом пользователи могут входить в систему, какие данные требуются для регистрации нового пользователя и какие дополнительные шаги необходимо выполнить для подтверждения адреса электронной почты.
